apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: poddebug-so
  namespace: default
  labels:
    deploymentName: poddebug-deployment
spec:
  scaleTargetRef:
    deploymentName: poddebug-deployment
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.prom.svc.cluster.local:9090
      metricName: access_frequency
      threshold: '3'
      query: sum(rate(http_requests[2m]))
